from decouple import config

TWITTER_BEARER_TOKEN = config("TWITTER_BEARER_TOKEN")

BINANCE_KEY = config("BINANCE_KEY")
BINANCE_SECRET = config("BINANCE_SECRET")

BINANCE_KEY_TEST = config("BINANCE_KEY_TEST")
BINANCE_SECRET_TEST = config("BINANCE_SECRET_TEST")
